# Generated by Django 4.1.5 on 2023-01-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('age', models.IntegerField(default=6)),
                ('class_number', models.IntegerField()),
            ],
            options={
                'ordering': ['class_number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('age', models.IntegerField(default=6)),
                ('class_number_student', models.IntegerField()),
            ],
            options={
                'ordering': ['class_number_student'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
