# Generated by Django 4.1.5 on 2023-01-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_itema_itemb_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('age', models.IntegerField(default=6)),
                ('new_name', models.CharField(max_length=125)),
            ],
            options={
                'ordering': ['-name'],
                'abstract': False,
            },
        ),
    ]
