# Generated by Django 4.1.5 on 2023-01-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_multitable'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMultiTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True)),
                ('age', models.IntegerField(blank=True, default=6, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MultiTable',
        ),
    ]
